-- Generated by psc-make version 0.6.2
module Control.Comonad where
import Prim ()
import Prelude ()
import Control.Extend ()
class (Control.Extend.Extend w) <= Comonad w where
  extract :: forall a. w a -> a
