-- Generated by psc-make version 0.6.2
module Control.Comonad.Trans where
import Prim ()
import Prelude ()
import Control.Comonad ()
class ComonadTrans f where
  lower :: forall w a. (Control.Comonad.Comonad w) => f w a -> w a
