-- Generated by psc-make version 0.6.2
module Data.Monoid.Endo where
import Prelude ()
import Prim ()
import Prelude ()
import Data.Monoid ()
newtype Endo (a :: *) = Endo (a -> a)
foreign import runEndo :: forall a. Data.Monoid.Endo.Endo a -> a -> a
foreign import instance semigroupEndo :: Prelude.Semigroup (Data.Monoid.Endo.Endo a)
foreign import instance monoidEndo :: Data.Monoid.Monoid (Data.Monoid.Endo.Endo a)
